
// All emojis that this extension uses
// Created using https://gist.github.com/Caellian/947e9b7b0f9d42278b9308765dc4ec08

var EMOJI_DICT = { 
"face, grin, grinning face":"😀", 
"face, grinning face with big eyes, mouth, open, smile":"😃", 
"eye, face, grinning face with smiling eyes, mouth, open, smile":"😄", 
"beaming face with smiling eyes, eye, face, grin, smile":"😁", 
"face, grinning squinting face, laugh, mouth, satisfied, smile":"😆", 
"cold, face, grinning face with sweat, open, smile, sweat":"😅", 
"face, floor, laugh, rofl, rolling, rolling on the floor laughing, rotfl":"🤣", 
"face, face with tears of joy, joy, laugh, tear":"😂", 
"face, slightly smiling face, smile":"🙂", 
"face, upside-down":"🙃", 
"disappear, dissolve, liquid, melt, melting face <!-- 1FAE0 -->":"🫠", 
"face, wink, winking face":"😉", 
"blush, eye, face, smile, smiling face with smiling eyes":"😊", 
"angel, face, fantasy, halo, innocent, smiling face with halo":"😇", 
"adore, crush, hearts, in love, smiling face with hearts":"🥰", 
"eye, face, love, smile, smiling face with heart-eyes":"😍", 
"eyes, face, grinning, star, star-struck":"🤩", 
"face, face blowing a kiss, kiss":"😘", 
"face, kiss, kissing face":"😗", 
"closed, eye, face, kiss, kissing face with closed eyes":"😚", 
"eye, face, kiss, kissing face with smiling eyes, smile":"😙", 
"grateful, proud, relieved, smiling, smiling face with tear, tear, touched":"🥲", 
"delicious, face, face savoring food, savouring, smile, yum":"😋", 
"face, face with tongue, tongue":"😛", 
"eye, face, joke, tongue, wink, winking face with tongue":"😜", 
"eye, goofy, large, small, zany face":"🤪", 
"eye, face, horrible, squinting face with tongue, taste, tongue":"😝", 
"face, money, money-mouth face, mouth":"🤑", 
"face, hug, hugging, open hands, smiling face, smiling face with open hands":"🤗", 
"face with hand over mouth, whoops":"🤭", 
"amazement, awe, disbelief, embarrass, face with open eyes and hand over mouth, scared, surprise <!-- 1FAE2 -->":"🫢", 
"captivated, face with peeking eye, peep, stare <!-- 1FAE3 -->":"🫣", 
"quiet, shush, shushing face":"🤫", 
"face, thinking":"🤔", 
"OK, salute, saluting face, sunny, troops, yes <!-- 1FAE1 -->":"🫡", 
"face, mouth, zip, zipper, zipper-mouth face":"🤐", 
"distrust, face with raised eyebrow, skeptic":"🤨", 
"deadpan, face, meh, neutral":"😐", 
"expressionless, face, inexpressive, meh, unexpressive":"😑", 
"face, face without mouth, mouth, quiet, silent":"😶", 
"depressed, disappear, dotted line face, hide, introvert, invisible <!-- 1FAE5 -->":"🫥", 
"face, smirk, smirking face":"😏", 
"face, unamused, unhappy":"😒", 
"eyeroll, eyes, face, face with rolling eyes, rolling":"🙄", 
"face, grimace, grimacing face":"😬", 
"face, lie, lying face, pinocchio":"🤥", 
"earthquake, face, shaking, shock, vibrate <!-- 1FAE8 -->":"🫨", 
"face, relieved":"😌", 
"dejected, face, pensive":"😔", 
"face, good night, sleep, sleepy face":"😪", 
"drooling, face":"🤤", 
"face, good night, sleep, sleeping face, ZZZ":"😴", 
"cold, doctor, face, face with medical mask, mask, sick":"😷", 
"face, face with thermometer, ill, sick, thermometer":"🤒", 
"bandage, face, face with head-bandage, hurt, injury":"🤕", 
"face, nauseated, vomit":"🤢", 
"face vomiting, puke, sick, vomit":"🤮", 
"face, gesundheit, sneeze, sneezing face":"🤧", 
"feverish, heat stroke, hot, hot face, red-faced, sweating":"🥵", 
"blue-faced, cold, cold face, freezing, frostbite, icicles":"🥶", 
"dizzy, intoxicated, tipsy, uneven eyes, wavy mouth, woozy face":"🥴", 
"crossed-out eyes, dead, face, face with crossed-out eyes, knocked out":"😵", 
"exploding head, mind blown, shocked":"🤯", 
"cowboy, cowgirl, face, hat":"🤠", 
"celebration, hat, horn, party, partying face":"🥳", 
"disguise, disguised face, face, glasses, incognito, nose":"🥸", 
"bright, cool, face, smiling face with sunglasses, sun, sunglasses":"😎", 
"face, geek, nerd":"🤓", 
"face, face with monocle, monocle, stuffy":"🧐", 
"confused, face, meh":"😕", 
"disappointed, face with diagonal mouth, meh, skeptical, unsure <!-- 1FAE4 -->":"🫤", 
"face, worried":"😟", 
"face, frown, slightly frowning face":"🙁", 
"face, frown, frowning face":"☹", 
"face, face with open mouth, mouth, open, sympathy":"😮", 
"face, hushed, stunned, surprised":"😯", 
"astonished, face, shocked, totally":"😲", 
"dazed, face, flushed":"😳", 
"begging, mercy, pleading face, puppy eyes":"🥺", 
"angry, cry, face holding back tears, proud, resist, sad <!-- 1F979 -->":"🥹", 
"face, frown, frowning face with open mouth, mouth, open":"😦", 
"anguished, face":"😧", 
"face, fear, fearful, scared":"😨", 
"anxious face with sweat, blue, cold, face, rushed, sweat":"😰", 
"disappointed, face, relieved, sad but relieved face, whew":"😥", 
"cry, crying face, face, sad, tear":"😢", 
"cry, face, loudly crying face, sad, sob, tear":"😭", 
"face, face screaming in fear, fear, munch, scared, scream":"😱", 
"confounded, face":"😖", 
"face, persevere, persevering face":"😣", 
"disappointed, face":"😞", 
"cold, downcast face with sweat, face, sweat":"😓", 
"face, tired, weary":"😩", 
"face, tired":"😫", 
"bored, tired, yawn, yawning face":"🥱", 
"face, face with steam from nose, triumph, won":"😤", 
"angry, enraged, face, mad, pouting, rage, red":"😡", 
"anger, angry, face, mad":"😠", 
"face with symbols on mouth, swearing":"🤬", 
"face, fairy tale, fantasy, horns, smile, smiling face with horns":"😈", 
"angry face with horns, demon, devil, face, fantasy, imp":"👿", 
"death, face, fairy tale, monster, skull":"💀", 
"crossbones, death, face, monster, skull, skull and crossbones":"☠", 
"dung, face, monster, pile of poo, poo, poop":"💩", 
"clown, face":"🤡", 
"creature, face, fairy tale, fantasy, monster, ogre":"👹", 
"creature, face, fairy tale, fantasy, goblin, monster":"👺", 
"creature, face, fairy tale, fantasy, ghost, monster":"👻", 
"alien, creature, extraterrestrial, face, fantasy, ufo":"👽", 
"alien, creature, extraterrestrial, face, monster, ufo":"👾", 
"face, monster, robot":"🤖", 
"cat, face, grinning, mouth, open, smile":"😺", 
"cat, eye, face, grin, grinning cat with smiling eyes, smile":"😸", 
"cat, cat with tears of joy, face, joy, tear":"😹", 
"cat, eye, face, heart, love, smile, smiling cat with heart-eyes":"😻", 
"cat, cat with wry smile, face, ironic, smile, wry":"😼", 
"cat, eye, face, kiss, kissing cat":"😽", 
"cat, face, oh, surprised, weary":"🙀", 
"cat, cry, crying cat, face, sad, tear":"😿", 
"cat, face, pouting":"😾", 
"evil, face, forbidden, monkey, see, see-no-evil monkey":"🙈", 
"evil, face, forbidden, hear, hear-no-evil monkey, monkey":"🙉", 
"evil, face, forbidden, monkey, speak, speak-no-evil monkey":"🙊", 
"heart, letter, love, mail":"💌", 
"arrow, cupid, heart with arrow":"💘", 
"heart with ribbon, ribbon, valentine":"💝", 
"excited, sparkle, sparkling heart":"💖", 
"excited, growing, growing heart, nervous, pulse":"💗", 
"beating, beating heart, heartbeat, pulsating":"💓", 
"revolving, revolving hearts":"💞", 
"love, two hearts":"💕", 
"heart, heart decoration":"💟", 
"exclamation, heart exclamation, mark, punctuation":"❣", 
"break, broken, broken heart":"💔", 
"heart, red heart":"❤", 
"cute, heart, like, love, pink <!-- 1FA77 -->":"🩷", 
"orange, orange heart":"🧡", 
"yellow, yellow heart":"💛", 
"green, green heart":"💚", 
"blue, blue heart":"💙", 
"cyan, heart, light blue, light blue heart, teal <!-- 1FA75 -->":"🩵", 
"purple, purple heart":"💜", 
"brown, heart":"🤎", 
"black, black heart, evil, wicked":"🖤", 
"gray, grey heart, heart, silver, slate <!-- 1FA76 -->":"🩶", 
"heart, white":"🤍", 
"kiss, kiss mark, lips":"💋", 
"100, full, hundred, hundred points, score":"💯", 
"anger symbol, angry, comic, mad":"💢", 
"boom, collision, comic":"💥", 
"comic, dizzy, star":"💫", 
"comic, splashing, sweat, sweat droplets":"💦", 
"comic, dash, dashing away, running":"💨", 
"hole":"🕳", 
"balloon, bubble, comic, dialog, speech":"💬", 
"balloon, bubble, dialog, left speech bubble, speech":"🗨", 
"angry, balloon, bubble, mad, right anger bubble":"🗯", 
"balloon, bubble, comic, thought":"💭", 
"comic, good night, sleep, ZZZ":"💤", 
"hand, wave, waving":"👋", 
"backhand, raised, raised back of hand":"🤚", 
"finger, hand, hand with fingers splayed, splayed":"🖐", 
"hand, high 5, high five, raised hand":"✋", 
"finger, hand, spock, vulcan, vulcan salute":"🖖", 
"hand, right, rightward, rightwards hand <!-- 1FAF1 -->":"🫱", 
"hand, left, leftward, leftwards hand <!-- 1FAF2 -->":"🫲", 
"dismiss, drop, palm down hand, shoo <!-- 1FAF3 -->":"🫳", 
"beckon, catch, come, offer, palm up hand <!-- 1FAF4 -->":"🫴", 
"high five, leftward, leftwards pushing hand, push, refuse, stop, wait <!-- 1FAF7 -->":"🫷", 
"high five, push, refuse, rightward, rightwards pushing hand, stop, wait <!-- 1FAF8 -->":"🫸", 
"hand, OK":"👌", 
"fingers, hand gesture, interrogation, pinched, sarcastic":"🤌", 
"pinching hand, small amount":"🤏", 
"hand, v, victory":"✌", 
"cross, crossed fingers, finger, hand, luck":"🤞", 
"expensive, hand with index finger and thumb crossed, heart, love, money, snap <!-- 1FAF0 -->":"🫰", 
"hand, ILY, love-you gesture":"🤟", 
"finger, hand, horns, rock-on, sign of the horns":"🤘", 
"call, call me hand, hand, hang loose, Shaka":"🤙", 
"backhand, backhand index pointing left, finger, hand, index, point":"👈", 
"backhand, backhand index pointing right, finger, hand, index, point":"👉", 
"backhand, backhand index pointing up, finger, hand, point, up":"👆", 
"finger, hand, middle finger":"🖕", 
"backhand, backhand index pointing down, down, finger, hand, point":"👇", 
"finger, hand, index, index pointing up, point, up":"☝", 
"index pointing at the viewer, point, you <!-- 1FAF5 -->":"🫵", 
"+1, hand, thumb, thumbs up, up":"👍", 
"-1, down, hand, thumb, thumbs down":"👎", 
"clenched, fist, hand, punch, raised fist":"✊", 
"clenched, fist, hand, oncoming fist, punch":"👊", 
"fist, left-facing fist, leftwards":"🤛", 
"fist, right-facing fist, rightwards":"🤜", 
"clap, clapping hands, hand":"👏", 
"celebration, gesture, hand, hooray, raised, raising hands":"🙌", 
"heart hands, love <!-- 1FAF6 -->":"🫶", 
"hand, open, open hands":"👐", 
"palms up together, prayer":"🤲", 
"agreement, hand, handshake, meeting, shake":"🤝", 
"ask, folded hands, hand, high 5, high five, please, pray, thanks":"🙏", 
"hand, write, writing hand":"✍", 
"care, cosmetics, manicure, nail, polish":"💅", 
"camera, phone, selfie":"🤳", 
"biceps, comic, flex, flexed biceps, muscle":"💪", 
"accessibility, mechanical arm, prosthetic":"🦾", 
"accessibility, mechanical leg, prosthetic":"🦿", 
"kick, leg, limb":"🦵", 
"foot, kick, stomp":"🦶", 
"body, ear":"👂", 
"accessibility, ear with hearing aid, hard of hearing":"🦻", 
"body, nose":"👃", 
"brain, intelligent":"🧠", 
"anatomical, cardiology, heart, organ, pulse":"🫀", 
"breath, exhalation, inhalation, lungs, organ, respiration":"🫁", 
"dentist, tooth":"🦷", 
"bone, skeleton":"🦴", 
"eye, eyes, face":"👀", 
"body, eye":"👁", 
"body, tongue":"👅", 
"lips, mouth":"👄", 
"anxious, biting lip, fear, flirting, nervous, uncomfortable, worried <!-- 1FAE6 -->":"🫦", 
"baby, young":"👶", 
"child, gender-neutral, unspecified gender, young":"🧒", 
"boy, young":"👦", 
"girl, Virgo, young, zodiac":"👧", 
"adult, gender-neutral, person, unspecified gender":"🧑", 
"blond, blond-haired person, hair, person: blond hair":"👱", 
"adult, man":"👨", 
"beard, person, person: beard":"🧔", 
"adult, woman":"👩", 
"adult, gender-neutral, old, older person, unspecified gender":"🧓", 
"adult, man, old":"👴", 
"adult, old, woman":"👵", 
"frown, gesture, person frowning":"🙍", 
"gesture, person pouting, pouting":"🙎", 
"forbidden, gesture, hand, person gesturing NO, prohibited":"🙅", 
"gesture, hand, OK, person gesturing OK":"🙆", 
"hand, help, information, person tipping hand, sassy, tipping":"💁", 
"gesture, hand, happy, person raising hand, raised":"🙋", 
"accessibility, deaf, deaf person, ear, hear":"🧏", 
"apology, bow, gesture, person bowing, sorry":"🙇", 
"disbelief, exasperation, face, palm, person facepalming":"🤦", 
"doubt, ignorance, indifference, person shrugging, shrug":"🤷", 
"cop, officer, police":"👮", 
"detective, sleuth, spy":"🕵", 
"guard":"💂", 
"fighter, hidden, ninja, stealth":"🥷", 
"construction, hat, worker":"👷", 
"monarch, noble, person with crown, regal, royalty <!-- 1FAC5 -->":"🫅", 
"prince":"🤴", 
"fairy tale, fantasy, princess":"👸", 
"person wearing turban, turban":"👳", 
"cap, gua pi mao, hat, person, person with skullcap, skullcap":"👲", 
"headscarf, hijab, mantilla, tichel, woman with headscarf":"🧕", 
"groom, person, person in tuxedo, tuxedo":"🤵", 
"bride, person, person with veil, veil, wedding":"👰", 
"pregnant, woman":"🤰", 
"belly, bloated, full, pregnant, pregnant man <!-- 1FAC3 -->":"🫃", 
"belly, bloated, full, pregnant, pregnant person <!-- 1FAC4 -->":"🫄", 
"baby, breast, breast-feeding, nursing":"🤱", 
"angel, baby, face, fairy tale, fantasy":"👼", 
"celebration, Christmas, claus, father, santa":"🎅", 
"celebration, Christmas, claus, mother, Mrs.":"🤶", 
"good, hero, heroine, superhero, superpower":"🦸", 
"criminal, evil, superpower, supervillain, villain":"🦹", 
"mage, sorcerer, sorceress, witch, wizard":"🧙", 
"fairy, Oberon, Puck, Titania":"🧚", 
"Dracula, undead, vampire":"🧛", 
"mermaid, merman, merperson, merwoman":"🧜", 
"elf, magical":"🧝", 
"djinn, genie":"🧞", 
"undead, walking dead, zombie":"🧟", 
"fairy tale, fantasy, monster, troll <!-- 1F9CC -->":"🧌", 
"face, massage, person getting massage, salon":"💆", 
"barber, beauty, haircut, parlor, person getting haircut":"💇", 
"hike, person walking, walk, walking":"🚶", 
"person standing, stand, standing":"🧍", 
"kneel, kneeling, person kneeling":"🧎", 
"marathon, person running, running":"🏃", 
"dance, dancing, woman":"💃", 
"dance, dancing, man":"🕺", 
"business, person, person in suit levitating, suit":"🕴", 
"bunny ear, dancer, partying, people with bunny ears":"👯", 
"person in steamy room, sauna, steam room":"🧖", 
"climber, person climbing":"🧗", 
"fencer, fencing, person fencing, sword":"🤺", 
"horse, jockey, racehorse, racing":"🏇", 
"ski, skier, snow":"⛷", 
"ski, snow, snowboard, snowboarder":"🏂", 
"ball, golf, person golfing":"🏌", 
"person surfing, surfing":"🏄", 
"boat, person rowing boat, rowboat":"🚣", 
"person swimming, swim":"🏊", 
"ball, person bouncing ball":"⛹", 
"lifter, person lifting weights, weight":"🏋", 
"bicycle, biking, cyclist, person biking":"🚴", 
"bicycle, bicyclist, bike, cyclist, mountain, person mountain biking":"🚵", 
"cartwheel, gymnastics, person cartwheeling":"🤸", 
"people wrestling, wrestle, wrestler":"🤼", 
"person playing water polo, polo, water":"🤽", 
"ball, handball, person playing handball":"🤾", 
"balance, juggle, multitask, person juggling, skill":"🤹", 
"meditation, person in lotus position, yoga":"🧘", 
"bath, bathtub, person taking bath":"🛀", 
"good night, hotel, person in bed, sleep":"🛌", 
"couple, hand, holding hands, women, women holding hands":"👭", 
"couple, hand, hold, holding hands, man, woman, woman and man holding hands":"👫", 
"couple, Gemini, holding hands, man, men, men holding hands, twins, zodiac":"👬", 
"couple, kiss":"💏", 
"couple, couple with heart, love":"💑", 
"face, head, silhouette, speak, speaking":"🗣", 
"bust, bust in silhouette, silhouette":"👤", 
"bust, busts in silhouette, silhouette":"👥", 
"goodbye, hello, hug, people hugging, thanks":"🫂", 
"family":"👪", 
"clothing, footprint, footprints, print":"👣", 
"ginger, red hair, redhead":"🦰", 
"afro, curly, curly hair, ringlets":"🦱", 
"gray, hair, old, white":"🦳", 
"bald, chemotherapy, hairless, no hair, shaven":"🦲", 
"face, monkey":"🐵", 
"monkey":"🐒", 
"gorilla":"🦍", 
"ape, orangutan":"🦧", 
"dog, face, pet":"🐶", 
"dog, pet":"🐕", 
"accessibility, blind, guide, guide dog":"🦮", 
"dog, poodle":"🐩", 
"face, wolf":"🐺", 
"face, fox":"🦊", 
"curious, raccoon, sly":"🦝", 
"cat, face, pet":"🐱", 
"cat, pet":"🐈", 
"face, Leo, lion, zodiac":"🦁", 
"face, tiger":"🐯", 
"tiger":"🐅", 
"leopard":"🐆", 
"face, horse":"🐴", 
"animal, antlers, elk, mammal, moose <!-- 1FACE -->":"🫎", 
"animal, ass, burro, donkey, mammal, mule, stubborn <!-- 1FACF -->":"🫏", 
"equestrian, horse, racehorse, racing":"🐎", 
"face, unicorn":"🦄", 
"stripe, zebra":"🦓", 
"deer":"🦌", 
"bison, buffalo, herd, wisent":"🦬", 
"cow, face":"🐮", 
"bull, ox, Taurus, zodiac":"🐂", 
"buffalo, water":"🐃", 
"cow":"🐄", 
"face, pig":"🐷", 
"pig, sow":"🐖", 
"boar, pig":"🐗", 
"face, nose, pig":"🐽", 
"Aries, male, ram, sheep, zodiac":"🐏", 
"ewe, female, sheep":"🐑", 
"Capricorn, goat, zodiac":"🐐", 
"camel, dromedary, hump":"🐪", 
"bactrian, camel, hump, two-hump camel":"🐫", 
"alpaca, guanaco, llama, vicuña, wool":"🦙", 
"giraffe, spots":"🦒", 
"elephant":"🐘", 
"extinction, large, mammoth, tusk, woolly":"🦣", 
"rhinoceros":"🦏", 
"hippo, hippopotamus":"🦛", 
"face, mouse":"🐭", 
"mouse":"🐁", 
"rat":"🐀", 
"face, hamster, pet":"🐹", 
"bunny, face, pet, rabbit":"🐰", 
"bunny, pet, rabbit":"🐇", 
"chipmunk, squirrel":"🐿", 
"beaver, dam":"🦫", 
"hedgehog, spiny":"🦔", 
"bat, vampire":"🦇", 
"bear, face":"🐻", 
"face, koala, marsupial":"🐨", 
"face, panda":"🐼", 
"lazy, sloth, slow":"🦥", 
"fishing, otter, playful":"🦦", 
"skunk, stink":"🦨", 
"joey, jump, kangaroo, marsupial":"🦘", 
"badger, honey badger, pester":"🦡", 
"feet, paw, paw prints, print":"🐾", 
"bird, turkey":"🦃", 
"bird, chicken":"🐔", 
"bird, rooster":"🐓", 
"baby, bird, chick, hatching":"🐣", 
"baby, bird, chick":"🐤", 
"baby, bird, chick, front-facing baby chick":"🐥", 
"bird":"🐦", 
"bird, penguin":"🐧", 
"bird, dove, fly, peace":"🕊", 
"bird, eagle":"🦅", 
"bird, duck":"🦆", 
"bird, cygnet, swan, ugly duckling":"🦢", 
"bird, owl, wise":"🦉", 
"dodo, extinction, large, Mauritius":"🦤", 
"bird, feather, flight, light, plumage":"🪶", 
"flamboyant, flamingo, tropical":"🦩", 
"bird, ostentatious, peacock, peahen, proud":"🦚", 
"bird, parrot, pirate, talk":"🦜", 
"angelic, aviation, bird, flying, mythology, wing <!-- 1FABD -->":"🪽", 
"bird, fowl, goose, honk, silly <!-- 1FABF -->":"🪿", 
"face, frog":"🐸", 
"crocodile":"🐊", 
"terrapin, tortoise, turtle":"🐢", 
"lizard, reptile":"🦎", 
"bearer, Ophiuchus, serpent, snake, zodiac":"🐍", 
"dragon, face, fairy tale":"🐲", 
"dragon, fairy tale":"🐉", 
"brachiosaurus, brontosaurus, diplodocus, sauropod":"🦕", 
"T-Rex, Tyrannosaurus Rex":"🦖", 
"face, spouting, whale":"🐳", 
"whale":"🐋", 
"dolphin, flipper":"🐬", 
"sea lion, seal":"🦭", 
"fish, Pisces, zodiac":"🐟", 
"fish, tropical":"🐠", 
"blowfish, fish":"🐡", 
"fish, shark":"🦈", 
"octopus":"🐙", 
"shell, spiral":"🐚", 
"coral, ocean, reef <!-- 1FAB8 -->":"🪸", 
"burn, invertebrate, jelly, jellyfish, marine, ouch, stinger <!-- 1FABC -->":"🪼", 
"snail":"🐌", 
"butterfly, insect, pretty":"🦋", 
"bug, insect":"🐛", 
"ant, insect":"🐜", 
"bee, honeybee, insect":"🐝", 
"beetle, bug, insect":"🪲", 
"beetle, insect, lady beetle, ladybird, ladybug":"🐞", 
"cricket, grasshopper":"🦗", 
"cockroach, insect, pest, roach":"🪳", 
"insect, spider":"🕷", 
"spider, web":"🕸", 
"Scorpio, scorpion, zodiac":"🦂", 
"disease, fever, malaria, mosquito, pest, virus":"🦟", 
"disease, fly, maggot, pest, rotting":"🪰", 
"annelid, earthworm, parasite, worm":"🪱", 
"amoeba, bacteria, microbe, virus":"🦠", 
"bouquet, flower":"💐", 
"blossom, cherry, flower":"🌸", 
"flower, white flower":"💮", 
"Buddhism, flower, Hinduism, lotus, purity <!-- 1FAB7 -->":"🪷", 
"plant, rosette":"🏵", 
"flower, rose":"🌹", 
"flower, wilted":"🥀", 
"flower, hibiscus":"🌺", 
"flower, sun, sunflower":"🌻", 
"blossom, flower":"🌼", 
"flower, tulip":"🌷", 
"bluebonnet, flower, hyacinth, lavender, lupine, snapdragon <!-- 1FABB -->":"🪻", 
"seedling, young":"🌱", 
"boring, grow, house, nurturing, plant, potted plant, useless":"🪴", 
"evergreen tree, tree":"🌲", 
"deciduous, shedding, tree":"🌳", 
"palm, tree":"🌴", 
"cactus, plant":"🌵", 
"ear, grain, rice, sheaf of rice":"🌾", 
"herb, leaf":"🌿", 
"plant, shamrock":"☘", 
"4, clover, four, four-leaf clover, leaf":"🍀", 
"falling, leaf, maple":"🍁", 
"fallen leaf, falling, leaf":"🍂", 
"blow, flutter, leaf, leaf fluttering in wind, wind":"🍃", 
"empty nest, nesting <!-- 1FAB9 -->":"🪹", 
"nest with eggs, nesting <!-- 1FABA -->":"🪺", 
"mushroom, toadstool":"🍄", 
"fruit, grape, grapes":"🍇", 
"fruit, melon":"🍈", 
"fruit, watermelon":"🍉", 
"fruit, orange, tangerine":"🍊", 
"citrus, fruit, lemon":"🍋", 
"banana, fruit":"🍌", 
"fruit, pineapple":"🍍", 
"fruit, mango, tropical":"🥭", 
"apple, fruit, red":"🍎", 
"apple, fruit, green":"🍏", 
"fruit, pear":"🍐", 
"fruit, peach":"🍑", 
"berries, cherries, cherry, fruit, red":"🍒", 
"berry, fruit, strawberry":"🍓", 
"berry, bilberry, blue, blueberries, blueberry":"🫐", 
"food, fruit, kiwi":"🥝", 
"fruit, tomato, vegetable":"🍅", 
"food, olive":"🫒", 
"coconut, palm, piña colada":"🥥", 
"avocado, food, fruit":"🥑", 
"aubergine, eggplant, vegetable":"🍆", 
"food, potato, vegetable":"🥔", 
"carrot, food, vegetable":"🥕", 
"corn, ear, ear of corn, maize, maze":"🌽", 
"hot, pepper":"🌶", 
"bell pepper, capsicum, pepper, vegetable":"🫑", 
"cucumber, food, pickle, vegetable":"🥒", 
"bok choy, cabbage, kale, leafy green, lettuce":"🥬", 
"broccoli, wild cabbage":"🥦", 
"flavoring, garlic":"🧄", 
"flavoring, onion":"🧅", 
"food, nut, peanut, peanuts, vegetable":"🥜", 
"beans, food, kidney, legume <!-- 1FAD8 -->":"🫘", 
"chestnut, plant":"🌰", 
"beer, ginger root, root, spice <!-- 1FADA -->":"🫚", 
"beans, edamame, legume, pea, pod, vegetable <!-- 1FADB -->":"🫛", 
"bread, loaf":"🍞", 
"bread, breakfast, croissant, food, french, roll":"🥐", 
"baguette, bread, food, french":"🥖", 
"arepa, flatbread, lavash, naan, pita":"🫓", 
"pretzel, twisted":"🥨", 
"bagel, bakery, breakfast, schmear":"🥯", 
"breakfast, crêpe, food, hotcake, pancake, pancakes":"🥞", 
"breakfast, indecisive, iron, waffle":"🧇", 
"cheese, cheese wedge":"🧀", 
"bone, meat, meat on bone":"🍖", 
"bone, chicken, drumstick, leg, poultry":"🍗", 
"chop, cut of meat, lambchop, porkchop, steak":"🥩", 
"bacon, breakfast, food, meat":"🥓", 
"burger, hamburger":"🍔", 
"french, fries":"🍟", 
"cheese, pizza, slice":"🍕", 
"frankfurter, hot dog, hotdog, sausage":"🌭", 
"bread, sandwich":"🥪", 
"mexican, taco":"🌮", 
"burrito, mexican, wrap":"🌯", 
"mexican, tamale, wrapped":"🫔", 
"falafel, flatbread, food, gyro, kebab, stuffed":"🥙", 
"chickpea, falafel, meatball":"🧆", 
"breakfast, egg, food":"🥚", 
"breakfast, cooking, egg, frying, pan":"🍳", 
"casserole, food, paella, pan, shallow, shallow pan of food":"🥘", 
"pot, pot of food, stew":"🍲", 
"cheese, chocolate, fondue, melted, pot, Swiss":"🫕", 
"bowl with spoon, breakfast, cereal, congee":"🥣", 
"food, green, salad":"🥗", 
"popcorn":"🍿", 
"butter, dairy":"🧈", 
"condiment, salt, shaker":"🧂", 
"can, canned food":"🥫", 
"bento, box":"🍱", 
"cracker, rice":"🍘", 
"ball, Japanese, rice":"🍙", 
"cooked, rice":"🍚", 
"curry, rice":"🍛", 
"bowl, noodle, ramen, steaming":"🍜", 
"pasta, spaghetti":"🍝", 
"potato, roasted, sweet":"🍠", 
"kebab, oden, seafood, skewer, stick":"🍢", 
"sushi":"🍣", 
"fried, prawn, shrimp, tempura":"🍤", 
"cake, fish, fish cake with swirl, pastry, swirl":"🍥", 
"autumn, festival, moon cake, yuèbǐng":"🥮", 
"dango, dessert, Japanese, skewer, stick, sweet":"🍡", 
"dumpling, empanada, gyōza, jiaozi, pierogi, potsticker":"🥟", 
"fortune cookie, prophecy":"🥠", 
"oyster pail, takeout box":"🥡", 
"Cancer, crab, zodiac":"🦀", 
"bisque, claws, lobster, seafood":"🦞", 
"food, shellfish, shrimp, small":"🦐", 
"food, molusc, squid":"🦑", 
"diving, oyster, pearl":"🦪", 
"cream, dessert, ice, icecream, soft, sweet":"🍦", 
"dessert, ice, shaved, sweet":"🍧", 
"cream, dessert, ice, sweet":"🍨", 
"breakfast, dessert, donut, doughnut, sweet":"🍩", 
"cookie, dessert, sweet":"🍪", 
"birthday, cake, celebration, dessert, pastry, sweet":"🎂", 
"cake, dessert, pastry, shortcake, slice, sweet":"🍰", 
"bakery, cupcake, sweet":"🧁", 
"filling, pastry, pie":"🥧", 
"bar, chocolate, dessert, sweet":"🍫", 
"candy, dessert, sweet":"🍬", 
"candy, dessert, lollipop, sweet":"🍭", 
"custard, dessert, pudding, sweet":"🍮", 
"honey, honeypot, pot, sweet":"🍯", 
"baby, bottle, drink, milk":"🍼", 
"drink, glass, glass of milk, milk":"🥛", 
"beverage, coffee, drink, hot, steaming, tea":"☕", 
"drink, pot, tea, teapot":"🫖", 
"beverage, cup, drink, tea, teacup, teacup without handle":"🍵", 
"bar, beverage, bottle, cup, drink, sake":"🍶", 
"bar, bottle, bottle with popping cork, cork, drink, popping":"🍾", 
"bar, beverage, drink, glass, wine":"🍷", 
"bar, cocktail, drink, glass":"🍸", 
"bar, drink, tropical":"🍹", 
"bar, beer, drink, mug":"🍺", 
"bar, beer, clink, clinking beer mugs, drink, mug":"🍻", 
"celebrate, clink, clinking glasses, drink, glass":"🥂", 
"glass, liquor, shot, tumbler, whisky":"🥃", 
"drink, empty, glass, pouring liquid, spill <!-- 1FAD7 -->":"🫗", 
"cup with straw, juice, soda":"🥤", 
"bubble, milk, pearl, tea":"🧋", 
"beverage, box, juice, straw, sweet":"🧃", 
"drink, mate":"🧉", 
"cold, ice, ice cube, iceberg":"🧊", 
"chopsticks, hashi":"🥢", 
"cooking, fork, fork and knife with plate, knife, plate":"🍽", 
"cooking, cutlery, fork, fork and knife, knife":"🍴", 
"spoon, tableware":"🥄", 
"cooking, hocho, kitchen knife, knife, tool, weapon":"🔪", 
"condiment, container, empty, jar, sauce, store <!-- 1FAD9 -->":"🫙", 
"amphora, Aquarius, cooking, drink, jug, zodiac":"🏺", 
"Africa, earth, Europe, globe, globe showing Europe-Africa, world":"🌍", 
"Americas, earth, globe, globe showing Americas, world":"🌎", 
"Asia, Australia, earth, globe, globe showing Asia-Australia, world":"🌏", 
"earth, globe, globe with meridians, meridians, world":"🌐", 
"map, world":"🗺", 
"Japan, map, map of Japan":"🗾", 
"compass, magnetic, navigation, orienteering":"🧭", 
"cold, mountain, snow, snow-capped mountain":"🏔", 
"mountain":"⛰", 
"eruption, mountain, volcano":"🌋", 
"fuji, mount fuji, mountain":"🗻", 
"camping":"🏕", 
"beach, beach with umbrella, umbrella":"🏖", 
"desert":"🏜", 
"desert, island":"🏝", 
"national park, park":"🏞", 
"stadium":"🏟", 
"classical, classical building":"🏛", 
"building construction, construction":"🏗", 
"brick, bricks, clay, mortar, wall":"🧱", 
"boulder, heavy, rock, solid, stone":"🪨", 
"log, lumber, timber, wood":"🪵", 
"house, hut, roundhouse, yurt":"🛖", 
"houses":"🏘", 
"derelict, house":"🏚", 
"home, house":"🏠", 
"garden, home, house, house with garden":"🏡", 
"building, office building":"🏢", 
"Japanese, Japanese post office, post":"🏣", 
"European, post, post office":"🏤", 
"doctor, hospital, medicine":"🏥", 
"bank, building":"🏦", 
"building, hotel":"🏨", 
"hotel, love":"🏩", 
"convenience, store":"🏪", 
"building, school":"🏫", 
"department, store":"🏬", 
"building, factory":"🏭", 
"castle, Japanese":"🏯", 
"castle, European":"🏰", 
"chapel, romance, wedding":"💒", 
"Tokyo, tower":"🗼", 
"liberty, statue, Statue of Liberty":"🗽", 
"Christian, church, cross, religion":"⛪", 
"islam, mosque, Muslim, religion":"🕌", 
"hindu, temple":"🛕", 
"Jew, Jewish, religion, synagogue, temple":"🕍", 
"religion, shinto, shrine":"⛩", 
"islam, kaaba, Muslim, religion":"🕋", 
"fountain":"⛲", 
"camping, tent":"⛺", 
"fog, foggy":"🌁", 
"night, night with stars, star":"🌃", 
"city, cityscape":"🏙", 
"morning, mountain, sun, sunrise, sunrise over mountains":"🌄", 
"morning, sun, sunrise":"🌅", 
"city, cityscape at dusk, dusk, evening, landscape, sunset":"🌆", 
"dusk, sun, sunset":"🌇", 
"bridge, bridge at night, night":"🌉", 
"hot, hotsprings, springs, steaming":"♨", 
"carousel, horse":"🎠", 
"amusement park, play, playground slide, theme park <!-- 1F6DD -->":"🛝", 
"amusement park, ferris, theme park, wheel":"🎡", 
"amusement park, coaster, roller, theme park":"🎢", 
"barber, haircut, pole":"💈", 
"circus, tent":"🎪", 
"engine, locomotive, railway, steam, train":"🚂", 
"car, electric, railway, train, tram, trolleybus":"🚃", 
"high-speed train, railway, shinkansen, speed, train":"🚄", 
"bullet, railway, shinkansen, speed, train":"🚅", 
"railway, train":"🚆", 
"metro, subway":"🚇", 
"light rail, railway":"🚈", 
"railway, station, train":"🚉", 
"tram, trolleybus":"🚊", 
"monorail, vehicle":"🚝", 
"car, mountain, railway":"🚞", 
"car, tram, trolleybus":"🚋", 
"bus, vehicle":"🚌", 
"bus, oncoming":"🚍", 
"bus, tram, trolley, trolleybus":"🚎", 
"bus, minibus":"🚐", 
"ambulance, vehicle":"🚑", 
"engine, fire, truck":"🚒", 
"car, patrol, police":"🚓", 
"car, oncoming, police":"🚔", 
"taxi, vehicle":"🚕", 
"oncoming, taxi":"🚖", 
"automobile, car":"🚗", 
"automobile, car, oncoming":"🚘", 
"recreational, sport utility, sport utility vehicle":"🚙", 
"pick-up, pickup, truck":"🛻", 
"delivery, truck":"🚚", 
"articulated lorry, lorry, semi, truck":"🚛", 
"tractor, vehicle":"🚜", 
"car, racing":"🏎", 
"motorcycle, racing":"🏍", 
"motor, scooter":"🛵", 
"accessibility, manual wheelchair":"🦽", 
"accessibility, motorized wheelchair":"🦼", 
"auto rickshaw, tuk tuk":"🛺", 
"bicycle, bike":"🚲", 
"kick, scooter":"🛴", 
"board, skateboard":"🛹", 
"roller, skate":"🛼", 
"bus, stop":"🚏", 
"highway, motorway, road":"🛣", 
"railway, railway track, train":"🛤", 
"drum, oil":"🛢", 
"diesel, fuel, fuelpump, gas, pump, station":"⛽", 
"circle, tire, turn, wheel <!-- 1F6DE -->":"🛞", 
"beacon, car, light, police, revolving":"🚨", 
"horizontal traffic light, light, signal, traffic":"🚥", 
"light, signal, traffic, vertical traffic light":"🚦", 
"octagonal, sign, stop":"🛑", 
"barrier, construction":"🚧", 
"anchor, ship, tool":"⚓", 
"float, life preserver, life saver, rescue, ring buoy, safety <!-- 1F6DF -->":"🛟", 
"boat, resort, sailboat, sea, yacht":"⛵", 
"boat, canoe":"🛶", 
"boat, speedboat":"🚤", 
"passenger, ship":"🛳", 
"boat, ferry, passenger":"⛴", 
"boat, motor boat, motorboat":"🛥", 
"boat, passenger, ship":"🚢", 
"aeroplane, airplane":"✈", 
"aeroplane, airplane, small airplane":"🛩", 
"aeroplane, airplane, check-in, departure, departures":"🛫", 
"aeroplane, airplane, airplane arrival, arrivals, arriving, landing":"🛬", 
"hang-glide, parachute, parasail, skydive":"🪂", 
"chair, seat":"💺", 
"helicopter, vehicle":"🚁", 
"railway, suspension":"🚟", 
"cable, gondola, mountain, mountain cableway":"🚠", 
"aerial, cable, car, gondola, tramway":"🚡", 
"satellite, space":"🛰", 
"rocket, space":"🚀", 
"flying saucer, UFO":"🛸", 
"bell, bellhop, hotel":"🛎", 
"luggage, packing, travel":"🧳", 
"hourglass done, sand, timer":"⌛", 
"hourglass, hourglass not done, sand, timer":"⏳", 
"clock, watch":"⌚", 
"alarm, clock":"⏰", 
"clock, stopwatch":"⏱", 
"clock, timer":"⏲", 
"clock, mantelpiece clock":"🕰", 
"00, 12, 12:00, clock, o’clock, twelve":"🕛", 
"12, 12:30, clock, thirty, twelve, twelve-thirty":"🕧", 
"00, 1, 1:00, clock, o’clock, one":"🕐", 
"1, 1:30, clock, one, one-thirty, thirty":"🕜", 
"00, 2, 2:00, clock, o’clock, two":"🕑", 
"2, 2:30, clock, thirty, two, two-thirty":"🕝", 
"00, 3, 3:00, clock, o’clock, three":"🕒", 
"3, 3:30, clock, thirty, three, three-thirty":"🕞", 
"00, 4, 4:00, clock, four, o’clock":"🕓", 
"4, 4:30, clock, four, four-thirty, thirty":"🕟", 
"00, 5, 5:00, clock, five, o’clock":"🕔", 
"5, 5:30, clock, five, five-thirty, thirty":"🕠", 
"00, 6, 6:00, clock, o’clock, six":"🕕", 
"6, 6:30, clock, six, six-thirty, thirty":"🕡", 
"00, 7, 7:00, clock, o’clock, seven":"🕖", 
"7, 7:30, clock, seven, seven-thirty, thirty":"🕢", 
"00, 8, 8:00, clock, eight, o’clock":"🕗", 
"8, 8:30, clock, eight, eight-thirty, thirty":"🕣", 
"00, 9, 9:00, clock, nine, o’clock":"🕘", 
"9, 9:30, clock, nine, nine-thirty, thirty":"🕤", 
"00, 10, 10:00, clock, o’clock, ten":"🕙", 
"10, 10:30, clock, ten, ten-thirty, thirty":"🕥", 
"00, 11, 11:00, clock, eleven, o’clock":"🕚", 
"11, 11:30, clock, eleven, eleven-thirty, thirty":"🕦", 
"dark, moon, new moon":"🌑", 
"crescent, moon, waxing":"🌒", 
"first quarter moon, moon, quarter":"🌓", 
"gibbous, moon, waxing":"🌔", 
"full, moon":"🌕", 
"gibbous, moon, waning":"🌖", 
"last quarter moon, moon, quarter":"🌗", 
"crescent, moon, waning":"🌘", 
"crescent, moon":"🌙", 
"face, moon, new moon face":"🌚", 
"face, first quarter moon face, moon, quarter":"🌛", 
"face, last quarter moon face, moon, quarter":"🌜", 
"thermometer, weather":"🌡", 
"bright, rays, sun, sunny":"☀", 
"bright, face, full, moon":"🌝", 
"bright, face, sun, sun with face":"🌞", 
"ringed planet, saturn, saturnine":"🪐", 
"star":"⭐", 
"glittery, glow, glowing star, shining, sparkle, star":"🌟", 
"falling, shooting, star":"🌠", 
"milky way, space":"🌌", 
"cloud, weather":"☁", 
"cloud, sun, sun behind cloud":"⛅", 
"cloud, cloud with lightning and rain, rain, thunder":"⛈", 
"cloud, sun, sun behind small cloud":"🌤", 
"cloud, sun, sun behind large cloud":"🌥", 
"cloud, rain, sun, sun behind rain cloud":"🌦", 
"cloud, cloud with rain, rain":"🌧", 
"cloud, cloud with snow, cold, snow":"🌨", 
"cloud, cloud with lightning, lightning":"🌩", 
"cloud, tornado, whirlwind":"🌪", 
"cloud, fog":"🌫", 
"blow, cloud, face, wind":"🌬", 
"cyclone, dizzy, hurricane, twister, typhoon":"🌀", 
"rain, rainbow":"🌈", 
"closed umbrella, clothing, rain, umbrella":"🌂", 
"clothing, rain, umbrella":"☂", 
"clothing, drop, rain, umbrella, umbrella with rain drops":"☔", 
"rain, sun, umbrella, umbrella on ground":"⛱", 
"danger, electric, high voltage, lightning, voltage, zap":"⚡", 
"cold, snow, snowflake":"❄", 
"cold, snow, snowman":"☃", 
"cold, snow, snowman, snowman without snow":"⛄", 
"comet, space":"☄", 
"fire, flame, tool":"🔥", 
"cold, comic, drop, droplet, sweat":"💧", 
"ocean, water, wave":"🌊", 
"celebration, halloween, jack, jack-o-lantern, lantern":"🎃", 
"celebration, Christmas, tree":"🎄", 
"celebration, fireworks":"🎆", 
"celebration, fireworks, sparkle, sparkler":"🎇", 
"dynamite, explosive, firecracker, fireworks":"🧨", 
"*, sparkle, sparkles, star":"✨", 
"balloon, celebration":"🎈", 
"celebration, party, popper, tada":"🎉", 
"ball, celebration, confetti":"🎊", 
"banner, celebration, Japanese, tanabata tree, tree":"🎋", 
"bamboo, celebration, Japanese, pine, pine decoration":"🎍", 
"celebration, doll, festival, Japanese, Japanese dolls":"🎎", 
"carp, celebration, streamer":"🎏", 
"bell, celebration, chime, wind":"🎐", 
"celebration, ceremony, moon, moon viewing ceremony":"🎑", 
"gift, good luck, hóngbāo, lai see, money, red envelope":"🧧", 
"celebration, ribbon":"🎀", 
"box, celebration, gift, present, wrapped":"🎁", 
"celebration, reminder, ribbon":"🎗", 
"admission, admission tickets, ticket":"🎟", 
"admission, ticket":"🎫", 
"celebration, medal, military":"🎖", 
"prize, trophy":"🏆", 
"medal, sports medal":"🏅", 
"1st place medal, first, gold, medal":"🥇", 
"2nd place medal, medal, second, silver":"🥈", 
"3rd place medal, bronze, medal, third":"🥉", 
"ball, football, soccer":"⚽", 
"ball, baseball":"⚾", 
"ball, glove, softball, underarm":"🥎", 
"ball, basketball, hoop":"🏀", 
"ball, game, volleyball":"🏐", 
"american, ball, football":"🏈", 
"ball, football, rugby":"🏉", 
"ball, racquet, tennis":"🎾", 
"flying disc, ultimate":"🥏", 
"ball, bowling, game":"🎳", 
"ball, bat, cricket game, game":"🏏", 
"ball, field, game, hockey, stick":"🏑", 
"game, hockey, ice, puck, stick":"🏒", 
"ball, goal, lacrosse, stick":"🥍", 
"ball, bat, game, paddle, ping pong, table tennis":"🏓", 
"badminton, birdie, game, racquet, shuttlecock":"🏸", 
"boxing, glove":"🥊", 
"judo, karate, martial arts, martial arts uniform, taekwondo, uniform":"🥋", 
"goal, net":"🥅", 
"flag in hole, golf, hole":"⛳", 
"ice, skate":"⛸", 
"fish, fishing pole, pole":"🎣", 
"diving, diving mask, scuba, snorkeling":"🤿", 
"athletics, running, sash, shirt":"🎽", 
"ski, skis, snow":"🎿", 
"sled, sledge, sleigh":"🛷", 
"curling stone, game, rock":"🥌", 
"bullseye, dart, direct hit, game, hit, target":"🎯", 
"fluctuate, toy, yo-yo":"🪀", 
"fly, kite, soar":"🪁", 
"gun, handgun, pistol, revolver, tool, water, weapon":"🔫", 
"8, ball, billiard, eight, game, pool 8 ball":"🎱", 
"ball, crystal, fairy tale, fantasy, fortune, tool":"🔮", 
"magic, magic wand, witch, wizard":"🪄", 
"controller, game, video game":"🎮", 
"game, joystick, video game":"🕹", 
"game, slot, slot machine":"🎰", 
"dice, die, game":"🎲", 
"clue, interlocking, jigsaw, piece, puzzle":"🧩", 
"plaything, plush, stuffed, teddy bear, toy":"🧸", 
"celebration, party, piñata":"🪅", 
"dance, disco, glitter, mirror ball, party <!-- 1FAA9 -->":"🪩", 
"doll, nesting, nesting dolls, russia":"🪆", 
"card, game, spade suit":"♠", 
"card, game, heart suit":"♥", 
"card, diamond suit, game":"♦", 
"card, club suit, game":"♣", 
"chess, chess pawn, dupe, expendable":"♟", 
"card, game, joker, wildcard":"🃏", 
"game, mahjong, mahjong red dragon, red":"🀄", 
"card, flower, flower playing cards, game, Japanese, playing":"🎴", 
"art, mask, performing, performing arts, theater, theatre":"🎭", 
"art, frame, framed picture, museum, painting, picture":"🖼", 
"art, artist palette, museum, painting, palette":"🎨", 
"needle, sewing, spool, string, thread":"🧵", 
"embroidery, needle, sewing, stitches, sutures, tailoring":"🪡", 
"ball, crochet, knit, yarn":"🧶", 
"knot, rope, tangled, tie, twine, twist":"🪢", 
"clothing, eye, eyeglasses, eyewear, glasses":"👓", 
"dark, eye, eyewear, glasses, sunglasses":"🕶", 
"eye protection, goggles, swimming, welding":"🥽", 
"doctor, experiment, lab coat, scientist":"🥼", 
"emergency, safety, vest":"🦺", 
"clothing, necktie, tie":"👔", 
"clothing, shirt, t-shirt, tshirt":"👕", 
"clothing, jeans, pants, trousers":"👖", 
"neck, scarf":"🧣", 
"gloves, hand":"🧤", 
"coat, jacket":"🧥", 
"socks, stocking":"🧦", 
"clothing, dress":"👗", 
"clothing, kimono":"👘", 
"clothing, dress, sari":"🥻", 
"bathing suit, one-piece swimsuit":"🩱", 
"bathing suit, briefs, one-piece, swimsuit, underwear":"🩲", 
"bathing suit, pants, shorts, underwear":"🩳", 
"bikini, clothing, swim":"👙", 
"clothing, woman, woman’s clothes":"👚", 
"cooling, dance, fan, flutter, folding hand fan, hot, shy <!-- 1FAAD -->":"🪭", 
"clothing, coin, purse":"👛", 
"bag, clothing, handbag, purse":"👜", 
"bag, clothing, clutch bag, pouch":"👝", 
"bag, hotel, shopping, shopping bags":"🛍", 
"backpack, bag, rucksack, satchel, school":"🎒", 
"beach sandals, sandals, thong sandal, thong sandals, thongs, zōri":"🩴", 
"clothing, man, man’s shoe, shoe":"👞", 
"athletic, clothing, running shoe, shoe, sneaker":"👟", 
"backpacking, boot, camping, hiking":"🥾", 
"ballet flat, flat shoe, slip-on, slipper":"🥿", 
"clothing, heel, high-heeled shoe, shoe, woman":"👠", 
"clothing, sandal, shoe, woman, woman’s sandal":"👡", 
"ballet, ballet shoes, dance":"🩰", 
"boot, clothing, shoe, woman, woman’s boot":"👢", 
"Afro, comb, hair, pick <!-- 1FAAE -->":"🪮", 
"clothing, crown, king, queen":"👑", 
"clothing, hat, woman, woman’s hat":"👒", 
"clothing, hat, top, tophat":"🎩", 
"cap, celebration, clothing, graduation, hat":"🎓", 
"baseball cap, billed cap":"🧢", 
"army, helmet, military, soldier, warrior":"🪖", 
"aid, cross, face, hat, helmet, rescue worker’s helmet":"⛑", 
"beads, clothing, necklace, prayer, religion":"📿", 
"cosmetics, lipstick, makeup":"💄", 
"diamond, ring":"💍", 
"diamond, gem, gem stone, jewel":"💎", 
"mute, muted speaker, quiet, silent, speaker":"🔇", 
"soft, speaker low volume":"🔈", 
"medium, speaker medium volume":"🔉", 
"loud, speaker high volume":"🔊", 
"loud, loudspeaker, public address":"📢", 
"cheering, megaphone":"📣", 
"horn, post, postal":"📯", 
"bell":"🔔", 
"bell, bell with slash, forbidden, mute, quiet, silent":"🔕", 
"music, musical score, score":"🎼", 
"music, musical note, note":"🎵", 
"music, musical notes, note, notes":"🎶", 
"mic, microphone, music, studio":"🎙", 
"level, music, slider":"🎚", 
"control, knobs, music":"🎛", 
"karaoke, mic, microphone":"🎤", 
"earbud, headphone":"🎧", 
"radio, video":"📻", 
"instrument, music, sax, saxophone":"🎷", 
"accordion, concertina, squeeze box":"🪗", 
"guitar, instrument, music":"🎸", 
"instrument, keyboard, music, musical keyboard, piano":"🎹", 
"instrument, music, trumpet":"🎺", 
"instrument, music, violin":"🎻", 
"banjo, music, stringed":"🪕", 
"drum, drumsticks, music":"🥁", 
"beat, conga, drum, long drum, rhythm":"🪘", 
"instrument, maracas, music, percussion, rattle, shake <!-- 1FA87 -->":"🪇", 
"fife, flute, music, pipe, recorder, woodwind <!-- 1FA88 -->":"🪈", 
"cell, mobile, phone, telephone":"📱", 
"arrow, cell, mobile, mobile phone with arrow, phone, receive":"📲", 
"phone, telephone":"☎", 
"phone, receiver, telephone":"📞", 
"pager":"📟", 
"fax, fax machine":"📠", 
"battery":"🔋", 
"electronic, low battery, low energy <!-- 1FAAB -->":"🪫", 
"electric, electricity, plug":"🔌", 
"computer, laptop, pc, personal":"💻", 
"computer, desktop":"🖥", 
"computer, printer":"🖨", 
"computer, keyboard":"⌨", 
"computer, computer mouse":"🖱", 
"computer, trackball":"🖲", 
"computer, disk, minidisk, optical":"💽", 
"computer, disk, floppy":"💾", 
"CD, computer, disk, optical":"💿", 
"Blu-ray, computer, disk, DVD, optical":"📀", 
"abacus, calculation":"🧮", 
"camera, cinema, movie":"🎥", 
"cinema, film, frames, movie":"🎞", 
"cinema, film, movie, projector, video":"📽", 
"clapper, clapper board, movie":"🎬", 
"television, tv, video":"📺", 
"camera, video":"📷", 
"camera, camera with flash, flash, video":"📸", 
"camera, video":"📹", 
"tape, vhs, video, videocassette":"📼", 
"glass, magnifying, magnifying glass tilted left, search, tool":"🔍", 
"glass, magnifying, magnifying glass tilted right, search, tool":"🔎", 
"candle, light":"🕯", 
"bulb, comic, electric, idea, light":"💡", 
"electric, flashlight, light, tool, torch":"🔦", 
"bar, lantern, light, red, red paper lantern":"🏮", 
"diya, lamp, oil":"🪔", 
"book, cover, decorated, notebook, notebook with decorative cover":"📔", 
"book, closed":"📕", 
"book, open":"📖", 
"book, green":"📗", 
"blue, book":"📘", 
"book, orange":"📙", 
"book, books":"📚", 
"notebook":"📓", 
"ledger, notebook":"📒", 
"curl, document, page, page with curl":"📃", 
"paper, scroll":"📜", 
"document, page, page facing up":"📄", 
"news, newspaper, paper":"📰", 
"news, newspaper, paper, rolled, rolled-up newspaper":"🗞", 
"bookmark, mark, marker, tabs":"📑", 
"bookmark, mark":"🔖", 
"label":"🏷", 
"bag, dollar, money, moneybag":"💰", 
"coin, gold, metal, money, silver, treasure":"🪙", 
"banknote, bill, currency, money, note, yen":"💴", 
"banknote, bill, currency, dollar, money, note":"💵", 
"banknote, bill, currency, euro, money, note":"💶", 
"banknote, bill, currency, money, note, pound":"💷", 
"banknote, bill, fly, money, money with wings, wings":"💸", 
"card, credit, money":"💳", 
"accounting, bookkeeping, evidence, proof, receipt":"🧾", 
"chart, chart increasing with yen, graph, growth, money, yen":"💹", 
"email, envelope, letter":"✉", 
"e-mail, email, letter, mail":"📧", 
"e-mail, email, envelope, incoming, letter, receive":"📨", 
"arrow, e-mail, email, envelope, envelope with arrow, outgoing":"📩", 
"box, letter, mail, outbox, sent, tray":"📤", 
"box, inbox, letter, mail, receive, tray":"📥", 
"box, package, parcel":"📦", 
"closed, closed mailbox with raised flag, mail, mailbox, postbox":"📫", 
"closed, closed mailbox with lowered flag, lowered, mail, mailbox, postbox":"📪", 
"mail, mailbox, open, open mailbox with raised flag, postbox":"📬", 
"lowered, mail, mailbox, open, open mailbox with lowered flag, postbox":"📭", 
"mail, mailbox, postbox":"📮", 
"ballot, ballot box with ballot, box":"🗳", 
"pencil":"✏", 
"black nib, nib, pen":"✒", 
"fountain, pen":"🖋", 
"ballpoint, pen":"🖊", 
"paintbrush, painting":"🖌", 
"crayon":"🖍", 
"memo, pencil":"📝", 
"briefcase":"💼", 
"file, folder":"📁", 
"file, folder, open":"📂", 
"card, dividers, index":"🗂", 
"calendar, date":"📅", 
"calendar, tear-off calendar":"📆", 
"note, pad, spiral, spiral notepad":"🗒", 
"calendar, pad, spiral":"🗓", 
"card, index, rolodex":"📇", 
"chart, chart increasing, graph, growth, trend, upward":"📈", 
"chart, chart decreasing, down, graph, trend":"📉", 
"bar, chart, graph":"📊", 
"clipboard":"📋", 
"pin, pushpin":"📌", 
"pin, pushpin, round pushpin":"📍", 
"paperclip":"📎", 
"link, linked paperclips, paperclip":"🖇", 
"ruler, straight edge, straight ruler":"📏", 
"ruler, set, triangle, triangular ruler":"📐", 
"cutting, scissors, tool":"✂", 
"box, card, file":"🗃", 
"cabinet, file, filing":"🗄", 
"wastebasket":"🗑", 
"closed, locked":"🔒", 
"lock, open, unlock, unlocked":"🔓", 
"ink, lock, locked with pen, nib, pen, privacy":"🔏", 
"closed, key, lock, locked with key, secure":"🔐", 
"key, lock, password":"🔑", 
"clue, key, lock, old":"🗝", 
"hammer, tool":"🔨", 
"axe, chop, hatchet, split, wood":"🪓", 
"mining, pick, tool":"⛏", 
"hammer, hammer and pick, pick, tool":"⚒", 
"hammer, hammer and wrench, spanner, tool, wrench":"🛠", 
"dagger, knife, weapon":"🗡", 
"crossed, swords, weapon":"⚔", 
"bomb, comic":"💣", 
"boomerang, rebound, repercussion":"🪃", 
"archer, arrow, bow, bow and arrow, Sagittarius, zodiac":"🏹", 
"shield, weapon":"🛡", 
"carpenter, carpentry saw, lumber, saw, tool":"🪚", 
"spanner, tool, wrench":"🔧", 
"screw, screwdriver, tool":"🪛", 
"bolt, nut, nut and bolt, tool":"🔩", 
"cog, cogwheel, gear, tool":"⚙", 
"clamp, compress, tool, vice":"🗜", 
"balance, justice, Libra, scale, zodiac":"⚖", 
"accessibility, blind, white cane":"🦯", 
"link":"🔗", 
"chain, chains":"⛓", 
"catch, crook, curve, ensnare, hook, selling point":"🪝", 
"chest, mechanic, tool, toolbox":"🧰", 
"attraction, horseshoe, magnet, magnetic":"🧲", 
"climb, ladder, rung, step":"🪜", 
"alembic, chemistry, tool":"⚗", 
"chemist, chemistry, experiment, lab, science, test tube":"🧪", 
"bacteria, biologist, biology, culture, lab, petri dish":"🧫", 
"biologist, dna, evolution, gene, genetics, life":"🧬", 
"microscope, science, tool":"🔬", 
"science, telescope, tool":"🔭", 
"antenna, dish, satellite":"📡", 
"medicine, needle, shot, sick, syringe":"💉", 
"bleed, blood donation, drop of blood, injury, medicine, menstruation":"🩸", 
"doctor, medicine, pill, sick":"💊", 
"adhesive bandage, bandage":"🩹", 
"cane, crutch, disability, hurt, mobility aid, stick <!-- 1FA7C -->":"🩼", 
"doctor, heart, medicine, stethoscope":"🩺", 
"bones, doctor, medical, skeleton, x-ray <!-- 1FA7B -->":"🩻", 
"door":"🚪", 
"accessibility, elevator, hoist, lift":"🛗", 
"mirror, reflection, reflector, speculum":"🪞", 
"frame, fresh air, opening, transparent, view, window":"🪟", 
"bed, hotel, sleep":"🛏", 
"couch, couch and lamp, hotel, lamp":"🛋", 
"chair, seat, sit":"🪑", 
"toilet":"🚽", 
"force cup, plumber, plunger, suction, toilet":"🪠", 
"shower, water":"🚿", 
"bath, bathtub":"🛁", 
"bait, mouse trap, mousetrap, snare, trap":"🪤", 
"razor, sharp, shave":"🪒", 
"lotion, lotion bottle, moisturizer, shampoo, sunscreen":"🧴", 
"diaper, punk rock, safety pin":"🧷", 
"broom, cleaning, sweeping, witch":"🧹", 
"basket, farming, laundry, picnic":"🧺", 
"paper towels, roll of paper, toilet paper":"🧻", 
"bucket, cask, pail, vat":"🪣", 
"bar, bathing, cleaning, lather, soap, soapdish":"🧼", 
"bubbles, burp, clean, soap, underwater <!-- 1FAE7 -->":"🫧", 
"bathroom, brush, clean, dental, hygiene, teeth, toothbrush":"🪥", 
"absorbing, cleaning, porous, sponge":"🧽", 
"extinguish, fire, fire extinguisher, quench":"🧯", 
"cart, shopping, trolley":"🛒", 
"cigarette, smoking":"🚬", 
"coffin, death":"⚰", 
"cemetery, grave, graveyard, headstone, tombstone":"🪦", 
"ashes, death, funeral, urn":"⚱", 
"bead, charm, evil-eye, nazar, nazar amulet, talisman":"🧿", 
"amulet, Fatima, hamsa, hand, Mary, Miriam, protection <!-- 1FAAC -->":"🪬", 
"face, moai, moyai, statue":"🗿", 
"demonstration, picket, placard, protest, sign":"🪧", 
"credentials, ID, identification card, license, security <!-- 1FAAA -->":"🪪", 
"ATM, ATM sign, automated, bank, teller":"🏧", 
"litter, litter bin, litter in bin sign":"🚮", 
"drinking, potable, water":"🚰", 
"access, wheelchair symbol":"♿", 
"bathroom, lavatory, man, men’s room, restroom, toilet, WC":"🚹", 
"bathroom, lavatory, restroom, toilet, WC, woman, women’s room":"🚺", 
"bathroom, lavatory, restroom, toilet, WC":"🚻", 
"baby, baby symbol, changing":"🚼", 
"bathroom, closet, lavatory, restroom, toilet, water, WC":"🚾", 
"control, passport":"🛂", 
"customs":"🛃", 
"baggage, claim":"🛄", 
"baggage, left luggage, locker, luggage":"🛅", 
"warning":"⚠", 
"child, children crossing, crossing, pedestrian, traffic":"🚸", 
"entry, forbidden, no, not, prohibited, traffic":"⛔", 
"entry, forbidden, no, not, prohibited":"🚫", 
"bicycle, bike, forbidden, no, no bicycles, prohibited":"🚳", 
"forbidden, no, not, prohibited, smoking":"🚭", 
"forbidden, litter, no, no littering, not, prohibited":"🚯", 
"non-drinking, non-potable, water":"🚱", 
"forbidden, no, no pedestrians, not, pedestrian, prohibited":"🚷", 
"cell, forbidden, mobile, no, no mobile phones, phone":"📵", 
"18, age restriction, eighteen, no one under eighteen, prohibited, underage":"🔞", 
"radioactive, sign":"☢", 
"biohazard, sign":"☣", 
"arrow, cardinal, direction, north, up arrow":"⬆", 
"arrow, direction, intercardinal, northeast, up-right arrow":"↗", 
"arrow, cardinal, direction, east, right arrow":"➡", 
"arrow, direction, down-right arrow, intercardinal, southeast":"↘", 
"arrow, cardinal, direction, down, south":"⬇", 
"arrow, direction, down-left arrow, intercardinal, southwest":"↙", 
"arrow, cardinal, direction, left arrow, west":"⬅", 
"arrow, direction, intercardinal, northwest, up-left arrow":"↖", 
"arrow, up-down arrow":"↕", 
"arrow, left-right arrow":"↔", 
"left right arrow stroke":"↮", 
"arrow, right arrow curving left":"↩", 
"arrow, left arrow curving right":"↪", 
"arrow, right arrow curving up":"⤴", 
"arrow, down, right arrow curving down":"⤵", 
"arrow, clockwise, clockwise vertical arrows, reload":"🔃", 
"anticlockwise, arrow, counterclockwise, counterclockwise arrows button, withershins":"🔄", 
"arrow, BACK":"🔙", 
"arrow, END":"🔚", 
"arrow, mark, ON, ON!":"🔛", 
"arrow, SOON":"🔜", 
"arrow, TOP, up":"🔝", 
"place of worship, religion, worship":"🛐", 
"atheist, atom, atom symbol":"⚛", 
"Hindu, om, religion":"🕉", 
"David, Jew, Jewish, religion, star, star of David":"✡", 
"Buddhist, dharma, religion, wheel, wheel of dharma":"☸", 
"religion, tao, taoist, yang, yin":"☯", 
"Christian, cross, latin cross, religion":"✝", 
"Christian, cross, orthodox cross, religion":"☦", 
"islam, Muslim, religion, star and crescent":"☪", 
"peace, peace symbol":"☮", 
"candelabrum, candlestick, menorah, religion":"🕎", 
"dotted six-pointed star, fortune, star":"🔯", 
"khanda, religion, Sikh <!-- 1FAAF -->":"🪯", 
"Aries, ram, zodiac":"♈", 
"bull, ox, Taurus, zodiac":"♉", 
"Gemini, twins, zodiac":"♊", 
"Cancer, crab, zodiac":"♋", 
"Leo, lion, zodiac":"♌", 
"Virgo, zodiac":"♍", 
"balance, justice, Libra, scales, zodiac":"♎", 
"Scorpio, scorpion, scorpius, zodiac":"♏", 
"archer, Sagittarius, zodiac":"♐", 
"Capricorn, goat, zodiac":"♑", 
"Aquarius, bearer, water, zodiac":"♒", 
"fish, Pisces, zodiac":"♓", 
"bearer, Ophiuchus, serpent, snake, zodiac":"⛎", 
"arrow, crossed, shuffle tracks button":"🔀", 
"arrow, clockwise, repeat, repeat button":"🔁", 
"arrow, clockwise, once, repeat single button":"🔂", 
"arrow, play, play button, right, triangle":"▶", 
"arrow, double, fast, fast-forward button, forward":"⏩", 
"arrow, next scene, next track, next track button, triangle":"⏭", 
"arrow, pause, play, play or pause button, right, triangle":"⏯", 
"arrow, left, reverse, reverse button, triangle":"◀", 
"arrow, double, fast reverse button, rewind":"⏪", 
"arrow, last track button, previous scene, previous track, triangle":"⏮", 
"arrow, button, upwards button":"🔼", 
"arrow, double, fast up button":"⏫", 
"arrow, button, down, downwards button":"🔽", 
"arrow, double, down, fast down button":"⏬", 
"bar, double, pause, pause button, vertical":"⏸", 
"square, stop, stop button":"⏹", 
"circle, record, record button":"⏺", 
"eject, eject button":"⏏", 
"camera, cinema, film, movie":"🎦", 
"brightness, dim, dim button, low":"🔅", 
"bright, bright button, brightness":"🔆", 
"antenna, antenna bars, bar, cell, mobile, phone":"📶", 
"computer, internet, network, wi-fi, wifi, wireless <!-- 1F6DC -->":"🛜", 
"cell, mobile, mode, phone, telephone, vibration":"📳", 
"cell, mobile, off, phone, telephone":"📴", 
"female sign, woman":"♀", 
"male sign, man":"♂", 
"transgender, transgender symbol":"⚧", 
"×, cancel, multiplication, multiply, sign, x":"✖", 
"+, math, plus, sign":"➕", 
"-, −, math, minus, sign":"➖", 
"÷, divide, division, math, sign":"➗", 
"equality, heavy equals sign, math <!-- 1F7F0 -->":"🟰", 
"forever, infinity, unbounded, universal":"♾", 
"!, !!, bangbang, double exclamation mark, exclamation, mark":"‼", 
"!, !?, ?, exclamation, interrobang, mark, punctuation, question":"⁉", 
"?, mark, punctuation, question, red question mark":"❓", 
"?, mark, outlined, punctuation, question, white question mark":"❔", 
"!, exclamation, mark, outlined, punctuation, white exclamation mark":"❕", 
"!, exclamation, mark, punctuation, red exclamation mark":"❗", 
"dash, punctuation, wavy":"〰", 
"bank, currency, exchange, money":"💱", 
"currency, dollar, heavy dollar sign, money":"💲", 
"aesculapius, medical symbol, medicine, staff":"⚕", 
"recycle, recycling symbol":"♻", 
"fleur-de-lis":"⚜", 
"anchor, emblem, ship, tool, trident":"🔱", 
"badge, name":"📛", 
"beginner, chevron, Japanese, Japanese symbol for beginner, leaf":"🔰", 
"circle, hollow red circle, large, o, red":"⭕", 
"✓, button, check, mark":"✅", 
"✓, box, check, check box with check":"☑", 
"✓, check, mark":"✔", 
"×, cancel, cross, mark, multiplication, multiply, x":"❌", 
"×, cross mark button, mark, square, x":"❎", 
"curl, curly loop, loop":"➰", 
"curl, double, double curly loop, loop":"➿", 
"mark, part, part alternation mark":"〽", 
"*, asterisk, eight-spoked asterisk":"✳", 
"*, eight-pointed star, star":"✴", 
"*, sparkle":"❇", 
"C, copyright":"©", 
"R, registered":"®", 
"mark, TM, trade mark, trademark":"™", 
"ABCD, input, latin, letters, uppercase":"🔠", 
"abcd, input, latin, letters, lowercase":"🔡", 
"1234, input, numbers":"🔢", 
"〒♪&amp;%, input, input symbols":"🔣", 
"abc, alphabet, input, latin, letters":"🔤", 
"A, A button (blood type), blood type":"🅰", 
"AB, AB button (blood type), blood type":"🆎", 
"B, B button (blood type), blood type":"🅱", 
"CL, CL button":"🆑", 
"COOL, COOL button":"🆒", 
"FREE, FREE button":"🆓", 
"i, information":"ℹ", 
"ID, ID button, identity":"🆔", 
"circle, circled M, M":"Ⓜ", 
"NEW, NEW button":"🆕", 
"NG, NG button":"🆖", 
"blood type, O, O button (blood type)":"🅾", 
"OK, OK button":"🆗", 
"P, P button, parking":"🅿", 
"help, SOS, SOS button":"🆘", 
"mark, UP, UP!, UP! button":"🆙", 
"versus, VS, VS button":"🆚", 
"“here”, Japanese, Japanese “here” button, katakana, ココ":"🈁", 
"“service charge”, Japanese, Japanese “service charge” button, katakana, サ":"🈂", 
"“monthly amount”, ideograph, Japanese, Japanese “monthly amount” button, 月":"🈷", 
"“not free of charge”, ideograph, Japanese, Japanese “not free of charge” button, 有":"🈶", 
"“reserved”, ideograph, Japanese, Japanese “reserved” button, 指":"🈯", 
"“bargain”, ideograph, Japanese, Japanese “bargain” button, 得":"🉐", 
"“discount”, ideograph, Japanese, Japanese “discount” button, 割":"🈹", 
"“free of charge”, ideograph, Japanese, Japanese “free of charge” button, 無":"🈚", 
"“prohibited”, ideograph, Japanese, Japanese “prohibited” button, 禁":"🈲", 
"“acceptable”, ideograph, Japanese, Japanese “acceptable” button, 可":"🉑", 
"“application”, ideograph, Japanese, Japanese “application” button, 申":"🈸", 
"“passing grade”, ideograph, Japanese, Japanese “passing grade” button, 合":"🈴", 
"“vacancy”, ideograph, Japanese, Japanese “vacancy” button, 空":"🈳", 
"“congratulations”, ideograph, Japanese, Japanese “congratulations” button, 祝":"㊗", 
"“secret”, ideograph, Japanese, Japanese “secret” button, 秘":"㊙", 
"“open for business”, ideograph, Japanese, Japanese “open for business” button, 営":"🈺", 
"“no vacancy”, ideograph, Japanese, Japanese “no vacancy” button, 満":"🈵", 
"circle, geometric, red":"🔴", 
"circle, orange":"🟠", 
"circle, yellow":"🟡", 
"circle, green":"🟢", 
"blue, circle, geometric":"🔵", 
"circle, purple":"🟣", 
"brown, circle":"🟤", 
"black circle, circle, geometric":"⚫", 
"circle, geometric, white circle":"⚪", 
"red, square":"🟥", 
"orange, square":"🟧", 
"square, yellow":"🟨", 
"green, square":"🟩", 
"blue, square":"🟦", 
"purple, square":"🟪", 
"brown, square":"🟫", 
"black large square, geometric, square":"⬛", 
"geometric, square, white large square":"⬜", 
"black medium square, geometric, square":"◼", 
"geometric, square, white medium square":"◻", 
"black medium-small square, geometric, square":"◾", 
"geometric, square, white medium-small square":"◽", 
"black small square, geometric, square":"▪", 
"geometric, square, white small square":"▫", 
"diamond, geometric, large orange diamond, orange":"🔶", 
"blue, diamond, geometric, large blue diamond":"🔷", 
"diamond, geometric, orange, small orange diamond":"🔸", 
"blue, diamond, geometric, small blue diamond":"🔹", 
"geometric, red, red triangle pointed up":"🔺", 
"down, geometric, red, red triangle pointed down":"🔻", 
"comic, diamond, diamond with a dot, geometric, inside":"💠", 
"button, geometric, radio":"🔘", 
"button, geometric, outlined, square, white square button":"🔳", 
"black square button, button, geometric, square":"🔲", 
"checkered, chequered, chequered flag, racing":"🏁", 
"post, triangular flag":"🚩", 
"celebration, cross, crossed, crossed flags, Japanese":"🎌", 
"black flag, waving":"🏴", 
"waving, white flag":"🏳"
};